name: Clone and add docs-early-access

description: Clone docs-early-access and copy its content into the repo (supports Windows, macOS, and Linux)

inputs:
  token:
    description: PAT
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Figure out which branch to checkout
      id: check-early-access
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: npm run what-docs-early-access-branch

    - name: Merge docs-early-access repo's folders
      shell: bash
      run: |
        src/early-access/scripts/merge-early-access.sh
        rm -fr docs-early-access
